version: '3'

services:
  reverse-proxy:
    container_name: 'myapp-reverse-proxy'
    restart: unless-stopped
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/config.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/config.yml:ro
      - ./config/certs:/etc/certs
  api:
    container_name: 'myapp-api'
    restart: unless-stopped
    # env_file:
    #   "./api/.env"
    build: api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    expose:
      - 4000
  web:
    container_name: 'myapp-web'
    restart: unless-stopped
    env_file: .env
    build: web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web-http.rule=Host(`${VITE_DOMAIN_NAME}.localhost`)'
      - 'traefik.http.routers.web-http.service=web'
      - 'traefik.http.routers.web-http.entrypoints=web'
      - 'traefik.http.routers.web-https.rule=Host(`${VITE_DOMAIN_NAME}.localhost`)'
      - 'traefik.http.routers.web-https.service=web'
      - 'traefik.http.routers.web-https.entrypoints=websecure'
      - 'traefik.http.routers.web-https.tls=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
      - 'traefik.http.services.web.loadbalancer.sticky=true'
    depends_on:
      - api
  mongo:
    container_name: 'myapp-mongo'
    restart: unless-stopped
    image: mongo:4.2.0
    volumes:
      - mongodata:/data/db:rw
    expose:
      - 27017
volumes:
  mongodata: